package top.mothership.cabbage.enums;

public enum Parameters {
    USERNAME, MODE, DAY, USER_ID, QQ, GROUPID, ROLE, FLAG, HOUR, NUM,
    OSU_SEARCH_PARAMETER,
    //重要！URL必须是冒号后面的"第三"参数（否则会将一部分的URL解析为第三参数）
    USERNAME_LIST, FILENAME, URL, SECOND, AT, BEATMAP_ID,
    SHADOWSOCKS_NUMBER, SHADOWSOCKS_USER, SHADOWSOCKS_CONFIRM, SHADOWSOCKS_COUNT
}
